name: Assign PR team labels
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setting labels
        uses: Dimfacion/auto-label@1.0.0
        with:
          repo-token: ${{ secrets.TOKEN }}
          labels_by_organization: '{}'