name: Assign PR team labels
on:
  pull_request:
    branches:
      - main

jobs:
  team-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Dimfacion/auto-label@v1.0.0
        with:
          repo-token: ${{ secrets.TOKEN }}
          labels_by_organization: "['OpenBAS-Platform': ['good-job']]"